default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT' || '5432'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

